name: Deploy CDK Stack

on:
    push:
        branches: ['main', 'development']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10.9'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                cd citybikes_infra
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: Install AWS CDK
              run: npm install -g aws-cdk

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Deploy CDK Stack
              run: |
                cd citybikes_infra
                source .venv/bin/activate
                cdk deploy --require-approval never --verbose
